spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    username: root
    password: relax@#2021
    url: jdbc:mysql://47.97.60.36:3306/relax?useAffectedRows=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    static-path-pattern: /**

server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.text.demo.entity

#messageTime: 60000    # 短信验证码60000=1分钟
serverUrl:  ../static/
#  http://47.97.60.36/
